### PR TITLE
Updating project and adding client roles

### PR DESCRIPTION
**Pull request by Samy-T**
Added:
- Employee Model
- CreateEmployeeOp
- ClientRoles:
     - GetRestaurantOp
     - GetMenusOp
- CreateMenuItemOp

### CODE REVIEW

**Comment by cosmintiru** [comment]
@Samy-T can you please work out your sln file? I think that I've mentioned this in the previous PR too. Currently your projects load using an absolute file path, which won't work anywhere apart from your machine.
```
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Demo", "D:\The Access Group Lab\access-ac-labs-2020\Turculescu_Samuel\Week_2\Demo\Demo.csproj", "{E5FF4B77-3E45-4F62-BC44-81FC0C9F3309}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Domain", "D:\The Access Group Lab\access-ac-labs-2020\Turculescu_Samuel\Week_2\Domain\Domain.csproj", "{CAD60E39-56CC-4F71-8E1B-0443FCDAD249}"
EndProject
Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Infra", "D:\The Access Group Lab\access-ac-labs-2020\Turculescu_Samuel\Week_2\Infra\Infra.csproj", "{063F4D15-8942-4936-926A-997972A751CD}"
EndProject
```

Can you switch to relative paths? I think that I might have pasted the correct code in the previous PR.

**Comment by Samy-T** [comment]
I fixed this problem in previous PR. Is it still loading using an absolute file path?

**Comment by cosmintiru** [comment]
> I fixed this problem in previous PR. Is it still loading using an absolute file path?

My bad, it's ok now.

**Comment by Samy-T** [comment]
Ok!

**Comment by Samy-T** [comment]
Added:
- Cart and CartItem Models
- Client Roles:
    - AddToCart
    - ChangeQuantityOp
    - PlaceOrderOp
    - GetOrderStatus

**Comment by Samy-T** [comment]
Added:
- ClientRoles:
     - PayOrderOp
- EmployeeRoles:
     - SetMenuItemOp
     - AddMenuItemOp
     - ChangeMenuItemOp
     - GetOrdersOp
     - GetOrderStatusOp
     - SetOrderStatusOp
     - CreatePaymentRequest

**Pull request merged**
